name: PyPI Release Only

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to release (e.g. v0.6.0)'
        required: true

jobs:
  pypi-release:
    name: Publish Python Wheel to PyPi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Setup Python (for maturin)
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install maturin
        run: pip install maturin

      - name: Build and publish
        working-directory: epimetheus-py
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          docker run --rm \
                      -e PYPI_TOKEN="$PYPI_TOKEN" \
                      -v "${{ github.workspace }}":/io \
                      -w /io \
                      --entrypoint bash \
                      ghcr.io/pyo3/maturin:latest \
                        -c "apt-get update && apt-get install -y pkg-config libssl-dev && maturin publish \
                          --manifest-path epimetheus-py/Cargo.toml \
                          --username __token__ \
                          --password \"$PYPI_TOKEN\""
